######################################################################
# Automatically generated by qmake (3.0) Tue Jun 24 22:03:45 2014
######################################################################

QT += opengl widgets
CONFIG += c++11
QMAKE_CXXFLAGS += -W -Wall -g 
LIBS += -lGL -lGLU -lopenal -lalut
TEMPLATE = app
TARGET = OpenAL
INCLUDEPATH += .

# Input
HEADERS += SoundManager.h AppWindow.hpp
SOURCES += main.cpp SoundManager.cpp AppWindow.cpp
