######################################################################
# Automatically generated by qmake (3.0) Wed Jun 25 12:08:22 2014
######################################################################

QT += opengl widgets
CONFIG += c++11
QMAKE_CXXFLAGS += -W -Wall -g 
LIBS += -lGL -lGLU -lglut
TEMPLATE = app
TARGET = QtShaders
INCLUDEPATH += .

# Input
HEADERS += AppWindow.hpp
SOURCES += AppWindow.cpp main.cpp 
